version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts-jdk11'
    container_name: 'jenkins-casare-int'
    hostname: 'jenkins-casare-int'
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - '/data/jenkins_custom/jenkins_home:/var/jenkins_home'
