version: '3'
services:
  jenkins:
    image: 'aramirol/jenkins-custom:latest'
    container_name: 'jenkins-demo-lab'
    hostname: 'jenkins-demo-lab'
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - '/data/jenkins_custom/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
