name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Test if the image can be built. 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jenkins-custom:test
      
    # Delete the image built before.  
    - name: Delete the Docker image
      run: docker rmi -f jenkins-custom:test
