name: Docker Image CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    

    steps:
      # Check out the repo
      - name: Check out the repo
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      # Read Image tag
      - name: Read Image tag
        id: tag
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.imagetag.cfg

      # Build and push Docker latest image
      - name: Build and push Docker image - latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: aramirol/jenkins-custom:latest
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker tagged image
      - name: Build and push Docker image - ${{ steps.tag.outputs.content }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: aramirol/jenkins-custom:${{ steps.tag.outputs.content }}
          labels: ${{ steps.meta.outputs.labels }}
